---
title: "testing"
author: "Luke Vawter"
date: "11/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#construct path for daily flows data
first_of_year = as.Date("2019-1-1")

daily_start = paste0(format(first_of_year,"%m"),"%2F",format(first_of_year,"%d"), "%2F",format(first_of_year,"20%y"))
print(daily_start)

daily_end = paste0(format((date_today0 - 10),"%m"),"%2F",format((date_today0 - 10),"%d"), "%2F",format((date_today0 - 10),"20%y"))

full_daily_url = paste0("https://icprbcoop.org/drupal4/icprb/flow-data?","startdate=", daily_start,"&enddate=" ,daily_end, "&format=daily&submit=Submit")

#import the data from sarah's site
flows_daily_old.df <- data.table::fread(full_daily_url, header = TRUE,
                                    data.table = FALSE,   colClasses = c("character", rep("numeric", 31)), # force cols 2-32 numeric
                                    na.strings = c("eqp", "Ice", "Bkw", "", "#N/A", -999999),
                                    col.names = list_gage_locations)
#write dataframe to file
write.csv(flows_daily_old.df, paste0(ts_path, "download_data_fd_old.csv"), row.names=FALSE)




#construct file path
date_minus_five = (date_today0 - 10) - 5
hourly_start = paste0(format(date_minus_five,"%m"),"%2F",format(date_minus_five,"%d"), "%2F",format(date_minus_five,"20%y"))

hourly_end = paste0(format((date_today0 - 10),"%m"),"%2F",format((date_today0 - 10),"%d"), "%2F",format((date_today0 - 10),"20%y"))

full_hourly_url = paste0("https://icprbcoop.org/drupal4/icprb/flow-data?","startdate=", hourly_start,"&enddate=" ,hourly_end, "&format=hourly&submit=Submit")

#import the hourly flows data from sarah's site
flows_hourly_old.df <- data.table::fread(full_hourly_url, header = TRUE,
                                     data.table = FALSE, colClasses = c("character", rep("numeric", 31)), # force cols 2-32 numeric
                                     na.strings = c("eqp", "Ice", "Bkw", "", "#N/A", -999999),
                                     col.names = list_gage_locations)

  #write dataframe to file
  write.csv(flows_hourly_old.df, paste0(ts_path, "download_data_fh_old.csv"), row.names=FALSE)






```

